version: '3.7'
services:
  manutencao:
    image: httpd-centos
    container_name: manutencao
    build:
      context: ./docker
      network: host
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8080:80"
